databases:
  - name: SyncSchedule-db 
    databaseName: SyncSchedule
    user: SyncSchedule_user
    plan: free
    region: oregon 

services:
  - type: web
    name: SyncSchedule-app
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python project/mainproject/manage.py migrate
      python project/mainproject/manage.py collectstatic --noinput
    startCommand: gunicorn --chdir project/mainproject mainproject.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False" 
      - key: ALLOWED_HOSTS
        fromSecret: ALLOWED_HOSTS
      - key: DATABASE_URL
        fromDatabase:
          name: SyncSchedule-db
          property: connectionString